CREATE TABLE IF NOT EXISTS `post_topic` (
  `post_topic_code` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `post_topic_text` VARCHAR(32) NOT NULL,
  `date_created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `date_updated` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`post_topic_code`),
  INDEX `post_topic_BTREE` USING BTREE (`post_topic_text`) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci